### ISSUE TITLE
error during activation

### ISSUE THREAD

**Issue by mordi-d** [dhulme/money-manager#108]
According to https://stackoverflow.com/questions/69773818/npm-dependency-conflict
I reverted to previous versions to be able to install

Node: v14.17.1
npm: 6.14.13

But when running npm run dev
Error:

```
> money-manager@1.10.0 dev Downloads\money-manager-1.10.0
> node .electron-vue/dev-runner.js

         ___                      __
   __   /\_ \       __     ___   /\ \__    _ __    ___     ___              __  __  __  __     __
 / ,.`\ \//\ \    / ,.`\  /'___\ \ \ ,_\  /\` __\ / __`\ /' _ `\   _______ /\ \/\ \/\ \/\ \  / ,.`\
/\  __/   \_\ \_ /\  __/ /\ \__/  \ \ \/  \ \ \/ /\ \_\ \/\ \/\ \ /\______\\ \ \/ |\ \ \_\ \/\  __/
\ \____\  /\____\\ \____\\ \____\  \ \ \_  \ \_\ \ \____/\ \_\ \_\\/______/ \ \___/ \ \____/\ \____\
 \/____/  \/____/ \/____/ \/____/   \ \__\  \/_/  \/___/  \/_/\/_/           \/__/   \/___/  \/____/
                                     \/__/
  getting ready...

┏ Main Process ---------------

  compiling...

┗ ----------------------------

Downloads\money-manager-1.10.0\.electron-vue\dev-runner.js:99
      hotMiddleware.publish({ action: 'compiling' });
                    ^

TypeError: Cannot read property 'publish' of undefined
    at Downloads\money-manager-1.10.0\.electron-vue\dev-runner.js:99:21
    at Hook.eval [as callAsync] (eval at create (Downloads\money-manager-1.10.0\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (Downloads\money-manager-1.10.0\node_modules\tapable\lib\Hook.js:18:14)
    at run (Downloads\money-manager-1.10.0\node_modules\webpack\lib\Watching.js:168:33)
    at Downloads\money-manager-1.10.0\node_modules\webpack\lib\Watching.js:163:6
    at Compiler.readRecords (Downloads\money-manager-1.10.0\node_modules\webpack\lib\Compiler.js:986:5)
    at run (Downloads\money-manager-1.10.0\node_modules\webpack\lib\Watching.js:159:26)
    at Watching._go (Downloads\money-manager-1.10.0\node_modules\webpack\lib\Watching.js:218:3)
    at Watching._invalidate (Downloads\money-manager-1.10.0\node_modules\webpack\lib\Watching.js:395:9)
    at Downloads\money-manager-1.10.0\node_modules\webpack\lib\Watching.js:67:28
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! money-manager@1.10.0 dev: `node .electron-vue/dev-runner.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the money-manager@1.10.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     AppData\Roaming\npm-cache\_logs\2022-10-03T18_08_33_933Z-debug.log
```

I would love to hear what can be done

Thank you very much for the app, it's really convenient, simple and useful

**Comment by dhulme** [comment]
Will be fixed in v2.0.0
